# vim ft=yaml
language: python

git:
  # we use submodules to be managed with datalad
  submodules: false

python:
  - 2.7
  - 3.6

cache:
  - apt

env:
  global:
    # will be used in the matrix, where neither other variable is used
    - COVERAGE=coverage

before_install:

install:
  # Install standalone build of git-annex for the recent enough version
  - travis_retry sudo eatmydata apt-get install pandoc
  - cd ..; pip install -q codecov; cd -
  #- pip install -r requirements.txt

script:
  # Verify that setup.py build doesn't puke
  - python setup.py build
  # Test installation system-wide
  - sudo pip install -e .
  # Run tests
  - PATH=$PWD/tools/coverage-bin:$PATH
    python -m pytest -s -v --cov=code --cov-report=term-missing .

after_success:
  - coverage combine -a /tmp/.coverage-entrypoints-*
  - codecov
